spring.application.name=demo
logging.level.org.springframework.security=DEBUG
# spring.data.redis.host=redis-11494.c328.europe-west3-1.gce.redns.redis-cloud.com
# spring.data.redis.port=11494
# spring.data.redis.password=rcpF3KnchVJDkNpdeJisbgIN4ESvDEVq
spring.datasource.url=${pg_url}
spring.datasource.username=${pg_user}
spring.datasource.password=${pg_password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.servlet.session.timeout=15m
